version: 2.1

parameters:
  job_env:
    type: string
    default: "dev"

commands:
  dev:
    description: "Dev env"
    steps:
      - run: echo Hello World from Dev env
      
  prod:
    description: "Dev env"
    steps:
      - run: echo Hello World from Dev env
      
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - when:
          condition:
            equal: [ "main" << pipeline.git.branch >> ]
          steps:
            - prod
            
workflows:
  test-workflow:
    jobs:
      - build
  
